export enum PackagingMode {
  CARTON = 'CARTON',
  BOX = 'BOX',
  ROLL = 'ROLL',
  BAG = 'BAG',
  PACK = 'PACK',
  DOZEN = 'DOZEN',
  SATCHET = 'SATCHET',
  BOTTLE = 'BOTTLE',
  TIN = 'TIN',
  TRAY = 'TRAY',
  TUBE = 'TUBE',
  INCH = 'INCH',
  YARD = 'YARD',
  VIAL = 'VIAL',
  AMPULE = 'AMPULE',
  UNIT = 'UNIT',
  PILL = 'PILL',
  TABLET = 'TABLET',
  PIECE = 'PIECE',
}
